spring:
  config:
    activate:
      on-profile: prod

  datasource:
    driver-class-name: org.postgresql.Driver
    url:  ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never

#  data:
#    redis:
#      host: prod-redis
#      port: 6379

logging:
  level:
    org.springframework.boot.actuate: WARN

app:
  upload:
    path: /app/uploads
  checkout:
    base-url: https://prod-gorani.lab.terminal-lab.kr/pay